### ISSUE TITLE
TODO/FIXME Count 4

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/http-signature-zcap-invoke#9]
- [ ] TODO: replace these with faster base64 implementation
       Commit: (f9f1631) Add core files.
       File:  [util-browser.js:63](https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/master/util-browser.js#L63)
       Dave Longley commented a year ago

  - [ ] TODO: is this safe for general use on every browser that doesn't
       Commit: (f9f1631) Add core files.
       File:  [util-browser.js:50](https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/master/util-browser.js#L50)
       Dave Longley commented a year ago

  - [ ] FIXME: rudimentary relative URL resolution
       Commit: (f9f1631) Add core files.
       File:  [util-browser.js:18](https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/master/util-browser.js#L18)
       Dave Longley commented a year ago

  - [ ] TODO: allow for parameter for expiration window
       Commit: (f9f1631) Add core files.
       File:  [main.js:93](https://github.com/digitalbazaar/http-signature-zcap-invoke/blob/master/main.js#L93)
       Dave Longley commented a year ago

**Comment by dlongley** [comment]
Closing as addressed via addressed by #21.
